In [6]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Univariate Imputation

In [2]:
train_data = [[1, 2, 3], 
              [np.nan, 5, 6], 
              [7, np.nan, 9], 
              [np.nan, np.nan, np.nan]]

In [3]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(train_data)

SimpleImputer()

In [4]:
X = [[np.nan, 2, 4], 
     [6, np.nan, 9], 
     [7, np.nan, 1], 
     [np.nan, np.nan, np.nan]]
imp_mean.transform(X)

array([[4. , 2. , 4. ],
       [6. , 3.5, 9. ],
       [7. , 3.5, 1. ],
       [4. , 3.5, 6. ]])

**Summary**
- It only takes average of values that are not nan. 

# Multivariate Imputation

Case 1

In [7]:
imp1 = IterativeImputer(random_state=0)

X = [[np.nan, 2, 3], 
     [4, np.nan, 6], 
     [10, np.nan, 9]]

imp1.fit_transform(X)

array([[-1.999999,  2.      ,  3.      ],
       [ 4.      ,  2.      ,  6.      ],
       [10.      ,  2.      ,  9.      ]])

Case 2

In [8]:
imp2 = IterativeImputer(random_state=0)
imp2.fit([[7, 2, 3], 
              [4, np.nan, 6], 
              [10, 5, 9]])
X = [[np.nan, 2, 3], 
     [4, np.nan, 6], 
     [10, np.nan, 9]]
imp2.transform(X)

array([[ 6.95847623,  2.        ,  3.        ],
       [ 4.        ,  2.6000004 ,  6.        ],
       [10.        ,  4.99999933,  9.        ]])

Case 3

In [9]:
imp3 = IterativeImputer(max_iter=10, random_state=0)
imp3.fit([[1, 2], 
         [3, 6], 
         [4, 8], 
         [np.nan, 3], 
         [7, np.nan]])
X_test = [[np.nan, 2], 
          [6, np.nan], 
          [np.nan, 6]]
# the model learns that the second feature is double the first
print(np.round(imp3.transform(X_test)))

[[ 1.  2.]
 [ 6. 12.]
 [ 3.  6.]]
